# Generated by Django 5.0.6 on 2024-07-09 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='edad',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
