# Generated by Django 5.0.6 on 2024-06-24 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Camiseta',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('imagen', models.ImageField(upload_to='adTienda')),
                ('precio', models.DecimalField(decimal_places=0, max_digits=8)),
                ('tallas', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Registro',
        ),
        migrations.RemoveField(
            model_name='tiendaonline',
            name='imagen',
        ),
        migrations.RemoveField(
            model_name='tiendaonline',
            name='nombreCamiseta',
        ),
    ]
