# Generated by Django 5.0.6 on 2024-06-14 23:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0002_alter_tiendaonline_imagen'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('imagen', models.URLField()),
            ],
        ),
        migrations.RemoveField(
            model_name='envio',
            name='email',
        ),
        migrations.RemoveField(
            model_name='envio',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='tiendaonline',
            name='imagen',
        ),
        migrations.RemoveField(
            model_name='tiendaonline',
            name='nombreCamiseta',
        ),
        migrations.RemoveField(
            model_name='tiendaonline',
            name='precio',
        ),
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CarritoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('carrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.carrito')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.item')),
            ],
        ),
        migrations.AddField(
            model_name='carrito',
            name='items',
            field=models.ManyToManyField(through='aplicacion.CarritoItem', to='aplicacion.item'),
        ),
    ]
