# Generated by Django 5.0.6 on 2024-06-15 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0004_remove_carrito_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='imagen',
        ),
        migrations.AlterField(
            model_name='item',
            name='titulo',
            field=models.CharField(max_length=100),
        ),
    ]
