# Generated by Django 5.0.6 on 2024-06-25 02:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0004_producto_carrito_carritoitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carritoitem',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.camiseta'),
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
    ]
