# Generated by Django 5.0.6 on 2024-06-15 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0005_remove_item_imagen_alter_item_titulo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrito',
            name='items',
        ),
    ]
