# Generated by Django 5.0.6 on 2024-06-16 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0006_remove_carrito_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registro',
            name='contraseña',
        ),
        migrations.AddField(
            model_name='registro',
            name='contrasena',
            field=models.CharField(default='temporal', max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='registro',
            name='apellido',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='registro',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='registro',
            name='nombre',
            field=models.CharField(max_length=254),
        ),
    ]
