# Generated by Django 5.0.6 on 2024-06-26 00:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0006_detalleordencompra_ordencompra_delete_admin1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordencompra',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
