# Generated by Django 5.0.6 on 2024-06-26 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0007_alter_ordencompra_fecha_creacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordencompra',
            name='total',
        ),
    ]
