# Generated by Django 5.0.6 on 2024-06-16 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0007_remove_registro_contraseña_registro_contrasena_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Registro',
            new_name='Usuario',
        ),
    ]
