# Generated by Django 5.0.6 on 2024-06-26 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0009_detallepedido_pedido_detallepedido_pedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
