# Generated by Django 5.0.6 on 2024-06-25 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0012_remove_itemcarrito_carrito_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camiseta',
            name='imagen',
            field=models.ImageField(upload_to='camisetas/'),
        ),
    ]
