# Generated by Django 5.0.6 on 2024-06-17 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0013_usuario_groups_usuario_is_superuser_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
